"""motor_reservas

Revision ID: 0183aee27655
Revises: 6cf54ae5c551
Create Date: 2026-06-22 21:39:53.589413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0183aee27655'
down_revision: Union[str, Sequence[str], None] = '6cf54ae5c551'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agendamentos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sala_id', sa.UUID(), nullable=False),
    sa.Column('profissional_id', sa.UUID(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Integer(), nullable=False),
    sa.Column('hora_fim', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profissional_id'], ['profissionais.id'], ),
    sa.ForeignKeyConstraint(['sala_id'], ['salas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agendamentos')
    # ### end Alembic commands ###
