"""Cria_tabelas_iniciais

Revision ID: 6adeb2480ac7
Revises: 
Create Date: 2026-06-14 13:55:26.622429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6adeb2480ac7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist;")
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('especialidades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('unidades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('profissionais',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome_completo', sa.String(), nullable=False),
    sa.Column('registro_conselho', sa.String(), nullable=True),
    sa.Column('especialidade_id', sa.UUID(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['especialidade_id'], ['especialidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('setores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('unidade_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('setor_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('capacidade_profissionais', sa.Integer(), nullable=False),
    sa.Column('especialidade_exclusiva_id', sa.UUID(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['especialidade_exclusiva_id'], ['especialidades.id'], ),
    sa.ForeignKeyConstraint(['setor_id'], ['setores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grade_fixa',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profissional_id', sa.UUID(), nullable=False),
    sa.Column('sala_id', sa.UUID(), nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=False),
    sa.Column('hora_inicio', sa.Integer(), nullable=False),
    sa.Column('hora_fim', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profissional_id'], ['profissionais.id'], ),
    sa.ForeignKeyConstraint(['sala_id'], ['salas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservas_avulsas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profissional_id', sa.UUID(), nullable=False),
    sa.Column('sala_id', sa.UUID(), nullable=False),
    sa.Column('data_reserva', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Integer(), nullable=False),
    sa.Column('hora_fim', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profissional_id'], ['profissionais.id'], ),
    sa.ForeignKeyConstraint(['sala_id'], ['salas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('excecoes_diarias',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('grade_fixa_id', sa.UUID(), nullable=False),
    sa.Column('data_excecao', sa.Date(), nullable=False),
    sa.Column('hora_inicio_ausencia', sa.Integer(), nullable=False),
    sa.Column('hora_fim_ausencia', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grade_fixa_id'], ['grade_fixa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    op.execute("""
        ALTER TABLE grade_fixa ADD CONSTRAINT check_limite_expediente CHECK (hora_inicio >= 8 AND hora_fim <= 17);
        ALTER TABLE grade_fixa ADD CONSTRAINT check_validade_bloco CHECK (hora_inicio < hora_fim);
        ALTER TABLE grade_fixa ADD CONSTRAINT check_bloqueio_almoco CHECK (hora_inicio != 12 AND hora_fim != 13);
        
        ALTER TABLE reservas_avulsas ADD CONSTRAINT check_limite_expediente CHECK (hora_inicio >= 8 AND hora_fim <= 17);
        ALTER TABLE reservas_avulsas ADD CONSTRAINT check_validade_bloco CHECK (hora_inicio < hora_fim);
        
        ALTER TABLE grade_fixa ADD CONSTRAINT check_profissional_unico_horario 
        EXCLUDE USING gist (
            profissional_id WITH =, 
            dia_semana WITH =, 
            int4range(hora_inicio, hora_fim) WITH &&
        );
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('excecoes_diarias')
    op.drop_table('reservas_avulsas')
    op.drop_table('grade_fixa')
    op.drop_table('salas')
    op.drop_table('setores')
    op.drop_table('profissionais')
    op.drop_table('unidades')
    op.drop_table('especialidades')
    # ### end Alembic commands ###
