"""update_profissionais

Revision ID: 6cf54ae5c551
Revises: fd6015b4240a
Create Date: 2026-06-22 21:10:07.919375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cf54ae5c551'
down_revision: Union[str, Sequence[str], None] = 'fd6015b4240a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profissionais', sa.Column('especialidade', sa.String(), nullable=False))
    op.alter_column('profissionais', 'registro_conselho',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'profissionais', ['registro_conselho'])
    op.drop_constraint(op.f('profissionais_especialidade_id_fkey'), 'profissionais', type_='foreignkey')
    op.drop_column('profissionais', 'especialidade_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profissionais', sa.Column('especialidade_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('profissionais_especialidade_id_fkey'), 'profissionais', 'especialidades', ['especialidade_id'], ['id'])
    op.drop_constraint(None, 'profissionais', type_='unique')
    op.alter_column('profissionais', 'registro_conselho',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('profissionais', 'especialidade')
    # ### end Alembic commands ###
