"""make setor_id nullable

Revision ID: fd6015b4240a
Revises: 6adeb2480ac7
Create Date: 2026-06-15 15:35:38.223389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd6015b4240a'
down_revision: Union[str, Sequence[str], None] = '6adeb2480ac7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('salas', 'setor_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('salas', 'setor_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
